a=int(input("첫 번째 숫자를 입력해주세요"))
print(a)
b=int(input("두 번째 숫자를 입력해주세요"))
print(a+b)
c=int(input("세 번째 숫자를 입력해주세요"))
print(a+b+c)
d=int(input("네 번째 숫자를 입력해주세요"))
print(a+b+c+d)
e=int(input("다섯 번째 숫자를 입력해주세요"))
print(a+b+c+d+e)

