a=int(input("첫 번째 숫자를 입력해주세요"))
b=int(input("두 번째 숫자를 입력해주세요"))
print("더하기 연산 : "+ str(a+b))
print("빼기 연산 : "+ str(a-b))
print("곱하기 연산 : "+ str(a*b))
print("몫 연산 : "+ str(a//b))
print("나머지 연산 : "+ str(a%b))